jobs:
- job: Linux
  pool:
    vmImage: "Ubuntu 16.04"
  timeoutInMinutes: 120
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
  - script: |
      pip install --upgrade pip
      chmod +x .ci/install.sh
      ./.ci/install.sh
      chmod +x .ci/run.sh
      ./.ci/run.sh
    env:
      CONAN_USERNAME: $(CONAN_USERNAME)
      CONAN_CHANNEL: "stable"
      CONAN_UPLOAD: $(CONAN_UPLOAD)
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
  strategy:
    matrix:
      GCC 7 x86_64:
        CONAN_GCC_VERSIONS: 7
        CONAN_DOCKER_IMAGE: conanio/gcc7
        CONAN_ARCHS: "x86_64"
- job: macOS
  dependsOn: Linux # This job runs after Linux job is done
  condition: always() # Run regardless of Linux job 
  pool:
    vmImage: "macOS-10.13"
  timeoutInMinutes: 120
  steps:
  - script: |
      /bin/bash -c "sudo xcode-select -s /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"
      pip install --upgrade pip
      chmod +x .ci/install.sh
      ./.ci/install.sh
      chmod +x .ci/run.sh
      ./.ci/run.sh
    env:
      CONAN_USERNAME: $(CONAN_USERNAME)
      CONAN_CHANNEL: "stable"
      CONAN_UPLOAD: $(CONAN_UPLOAD)
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
  strategy:
    matrix:
      CLANG 10.0:
        CONAN_APPLE_CLANG_VERSIONS: 10.0
        XCODE_VERSION: 10
- job: Windows
  dependsOn: macOS # This job runs after macOS job is done
  condition: always() # Run regardless of macOS job 
  pool:
    vmImage: "windows-2019"
  timeoutInMinutes: 120
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      addToPath: true
      architecture: 'x64'  
  - script: |
      pip install --upgrade pip
      pip install conan --upgrade
      pip install conan_package_tools
      conan user
      python build.py
    env:
      CONAN_USERNAME: $(CONAN_USERNAME)
      CONAN_CHANNEL: "stable"
      CONAN_UPLOAD: $(CONAN_UPLOAD)
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
  strategy:
    matrix:
      MSVC16:
        CONAN_VISUAL_VERSIONS: 16
        CONAN_BUILD_TYPES: Release,Debug
        CONAN_ARCHS: "x86_64"
