find_path(PostgreSQL_INCLUDE_DIR NAMES postgres_ext.h PATHS ${CONAN_INCLUDE_DIRS_LIBPQ} NO_CMAKE_FIND_ROOT_PATH)
find_library(PostgreSQL_LIBRARY NAMES ${CONAN_LIBS_LIBPQ} PATHS ${CONAN_LIB_DIRS_LIBPQ} NO_CMAKE_FIND_ROOT_PATH)

MESSAGE("** PostgreSQL ALREADY FOUND BY CONAN!")
SET(PostgreSQL_FOUND TRUE)
MESSAGE("** FOUND PostgreSQL:  ${PostgreSQL_LIBRARY}")
MESSAGE("** FOUND PostgreSQL INCLUDE:  ${PostgreSQL_INCLUDE_DIR}")

set(PostgreSQL_INCLUDE_DIRS ${PostgreSQL_INCLUDE_DIR})
set(PostgreSQL_LIBRARIES ${PostgreSQL_LIBRARY})

mark_as_advanced(PostgreSQL_ROOT PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR)

set(PostgreSQL_MAJOR_VERSION "9")
set(PostgreSQL_MINOR_VERSION "6")
set(PostgreSQL_PATCH_VERSION "9")
